#!/usr/bin/expect -f

set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set timeout 1

spawn /tmp/Anaconda3-2020.02-Linux-x86_64.sh

match_max 100000

sleep 1

expect ">>> "

send -- "\r"

set FLAG true

while {$FLAG == true} {

	expect {
		"\[7m--More--\[27m" { send -- "\r" }
		default { send -- "yes\r"; set FLAG false }
	}

}

expect {
	default { puts "\n"; send -- "\n\r" }
}

expect "*>" {send -- "\r";}

expect "ERROR" {puts "CONDA IS ALREADY INSTALLED"}

expect "*>" {send -- "yes\r";}

